signal:
    nclass: 1
    nlayer: 1
    num_heads: 1
    hidden_dim: 6
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.0
    feat_dropout: 0.0
    prop_dropout: 0.0
    norm: 'none'
cora:
    nclass: 7
    nlayer: 5
    num_heads: 2
    hidden_dim: 48
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.6
    feat_dropout: 0.3
    prop_dropout: 0.5
    norm: 'none'
citeseer:
    nclass: 6
    nlayer: 1
    num_heads: 2
    hidden_dim: 32
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'none'
photo:
    nclass: 8
    nlayer: 2
    num_heads: 4
    hidden_dim: 32
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.5
    feat_dropout: 0.3
    prop_dropout: 0.2
    norm: 'none'
arxiv:
    nclass: 40
    nlayer: 1
    num_heads: 2
    hidden_dim: 512
    epoch: 2000
    lr: 0.001
    weight_decay: 0.001
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
chameleon:
    nclass: 5
    nlayer: 2
    num_heads: 4
    hidden_dim: 32
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.5
    feat_dropout: 0.4
    prop_dropout: 0.5
    norm: 'none'
squirrel:
    nclass: 5
    nlayer: 2
    num_heads: 2
    hidden_dim: 48
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.2
    feat_dropout: 0.4
    prop_dropout: 0.6
    norm: 'none'
actor:
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 32
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.0
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'none'
penn:
    nclass: 2
    nlayer: 1
    num_heads: 1
    hidden_dim: 28
    epoch: 2000
    lr: 0.001
    weight_decay: 0.001
    tran_dropout: 0.1
    feat_dropout: 0.4
    prop_dropout: 0.1
    norm: 'batch'
texas:
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 32
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.5
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'none'
cornell:
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 32
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.5
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'none'
wisconsin:
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 32
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.5
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'none'